<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentMigrator.Runner" />
    <PackageReference Include="FluentMigrator.Runner.SqlServer" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TildeSql.SqlMigrations\TildeSql.SqlMigrations.csproj" />
    <ProjectReference Include="..\TildeSql.SqlServer\TildeSql.SqlServer.csproj" />
  </ItemGroup>
</Project>