<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>12</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Basic.Reference.Assemblies" />
    <PackageReference Include="FluentMigrator" />
    <PackageReference Include="FluentMigrator.Runner" />
    <PackageReference Include="FluentMigrator.Runner.SqlServer" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MiniProfiler.Shared" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="RT.Comb" />
    <PackageReference Include="System.Linq.Async" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TildeSql.Humanizer\TildeSql.Humanizer.csproj" />
    <ProjectReference Include="..\TildeSql.JsonNet\TildeSql.JsonNet.csproj" />
    <ProjectReference Include="..\TildeSql.SqlMigrations\TildeSql.SqlMigrations.csproj" />
    <ProjectReference Include="..\TildeSql.SqlServer\TildeSql.SqlServer.csproj" />
    <ProjectReference Include="..\TildeSql\TildeSql.csproj" />
  </ItemGroup>
</Project>